version: '3'
services:
  ui:
    container_name: ui
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ui/public:/app/ui/public
      - ./ui/src:/app/ui/src
    networks:
      - default
    environment:
      - NODE_ENV=development
    stdin_open: true
    command: npm start
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "3001:3001"
      - "8000:8000"
    volumes:
      - ./api:/app/api
      - ./api/node_modules
    networks:
      - default
    environment:
      - NODE_ENV=development
    command: npm start
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./db/Dockerfile 
    networks:
      - default
    ports:
      - "27017:27017"
    command: mongod
  # test:
  #   container_name: test
  #   build:
  #     context: .
  #     dockerfile: ./api/Dockerfile_test
  #   networks:
  #     - default
  #   command: nodemon yarn jest
